name: Update Badge Status

on:
  release:
    types: [published]

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update release status
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -d '{
            "state": "success",
            "target_url": "https://github.com/${{ github.repository }}/actions/workflows/build.yaml",
            "description": "Release published and status updated",
            "context": "release-status"
          }'
